return {
	formatters_by_ft = {
		bash = { "shfmt" },
		go = { "goimports" },
		json = { "jq" },
		lua = { "stylua" },
		sh = { "shfmt" },
	},
	linters_by_ft = {
		bash = { "shellcheck" },
		json = { "jq" },
		sh = { "shellcheck" },
	},
	lsp_to_enable = {
		"bashls",
		"cssls",
		"emmet_language_server",
		"gopls",
		"html",
		"lua_ls",
		"ruff",
		"rust_analyzer",
		"ts_ls",
	},
	mason_to_install = {
		"bash-language-server",
		"css-lsp",
		"emmet-language-server",
		"goimports",
		"gopls",
		"html-lsp",
		"jq",
		"lua-language-server",
		"ruff",
		"rust-analyzer",
		"shellcheck",
		"shfmt",
		"stylua",
		"typescript-language-server",
	},
	mason_use_local = {
		["jq"] = "jq",
		["rust-analyzer"] = "rust-analyzer",
	},
	parsers = {
		"bash",
		"c",
		"cpp",
		"css",
		"go",
		"html",
		"javascript",
		"json",
		"markdown",
		"php",
		"python",
		"rust",
		"sql",
		"toml",
		"typescript",
		"yaml",
	},
	remap_parsers = {
		["sh"] = "bash",
	},
}
